- name: Disable Nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx version 1.24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy nginx configuration file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove Nginx data
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create file for Nginx data
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend app code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start Nginx systemd
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
