- name: Disable Nodejs and enable nodejs version 20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Include app_prereq task list in play
  ansible.builtin.include_tasks:
    file: app_prereq.yaml

- name: Install Nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Include systemd setup tasks list in play
  ansible.builtin.include_tasks:
    file: systemd_setup.yaml

#- name: Disable Nodejs and enable Nodejs 20
#  ansible.builtin.shell: dnf module disable nodejs -y ;dnf module enable nodejs:20 -y
#
#- name: Install NodeJS
#  ansible.builtin.dnf:
#    name: nodejs
#    state: installed
#
#- name: Include artifact_download
#  ansible.builtin.include_tasks:
#    file: artifact_download.yml
#
#- name: Install NodeJs Dependencies
#  ansible.builtin.shell: npm install
#  args:
#    chdir: /app
#
#- name: Include systemd_setup
#  ansible.builtin.include_tasks:
#    file: systemd_setup.yml


