- name: Install Python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: installed

- name: Include app_prereq tasks in the play
  ansible.builtin.include_tasks:
    file: app_prereq.yaml

- name: Install python dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Include systemd setup tasks in the play
  ansible.builtin.include_tasks:
    file: systemd_setup.yaml
